In [2]:
import pandas as pd

In [3]:
market1customers = pd.read_json(r"Data/Market 1 Customers.json")
market1deliveries = pd.read_csv(r"Data/Market 1 Deliveries.csv")
market1orders = pd.read_csv(r"Data/Market 1 Orders.csv")
market2customers = pd.read_json(r"Data/Market 2 Customers.json")
market2deliveries = pd.read_csv(r"Data/Market 2 Deliveries.csv")
market2orders = pd.read_csv(r"Data/Market 2 Orders.csv")

C:\Users\eyram\AppData\Local\Temp\ipykernel_2368\3753102694.py:2: DtypeWarning: Columns (12,14,16,19,30,31) have mixed types. Specify dtype option on import or set low_memory=False.
  market1deliveries = pd.read_csv(r"Data/Market 1 Deliveries.csv")

In [4]:
mergedcustomers = pd.merge(market1customers,market2customers,on='Customer ID',how='outer')
mergedorders = pd.merge(market1orders,market2orders,on='Order ID',how='outer')
mergeddeliveries = pd.merge(market1deliveries,market2deliveries,on='Task_ID',how='outer')

In [5]:
df = mergedorders
df.to_csv("df.csv",index=False)

In [6]:
mergedcustomers.to_csv("mergedcustomers.csv",index=False)
mergedorders.to_csv("mergedorders.csv",index=False)
mergeddeliveries.to_csv("mergeddeliveries.csv",index=False)

In [7]:
mergedcustomers = pd.read_csv(r"merges/mergedcustomers.csv")
mergedorders = pd.read_csv(r"merges/mergedorders.csv")
mergeddeliveries = pd.read_csv(r"merges/mergeddeliveries.csv")

C:\Users\eyram\AppData\Local\Temp\ipykernel_2368\2617377421.py:2: DtypeWarning: Columns (33,45,46,47,57,58,59,60,62,63,64,66,73,74,75,82,83,86,87) have mixed types. Specify dtype option on import or set low_memory=False.
  mergedorders = pd.read_csv(r"merges/mergedorders.csv")
C:\Users\eyram\AppData\Local\Temp\ipykernel_2368\2617377421.py:3: DtypeWarning: Columns (1,3,4,5,6,7,8,9,10,11,12,13,14,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,34,35,36,37,38,39,40,41,43,47,48,49,50,51,52,53,54,55,56,57,58,59) have mixed types. Specify dtype option on import or set low_memory=False.
  mergeddeliveries = pd.read_csv(r"merges/mergeddeliveries.csv")

In [8]:
mergedcustomers

,Customer ID,Last Used Platform_x,Is Blocked_x,Created At_x,Language_x,Outstanding Amount_x,Loyalty Points_x,Number of employees,Last Used Platform_y,Is Blocked_y,Created At_y,Language_y,Outstanding Amount_y,Loyalty Points_y,Number of Employees
0,3144837,WEB,0.0,2021-03-15T17:13:19.000Z,en,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0
1,3174590,WEB,0.0,2021-03-20T14:15:11.000Z,en,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0
2,3181998,WEB,0.0,2021-03-21T15:36:51.000Z,en,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0
3,3191244,WEB,0.0,2021-03-23T08:54:00.000Z,en,0.0,367.0,0.0,0,0.0,0,0,0.0,0.0,0.0
4,3274222,WEB,0.0,2021-04-06T13:52:39.000Z,en,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5267,5161258,0,0.0,0,0,0.0,0.0,0.0,WEB,0.0,2022-02-11T07:11:38.000Z,en,0.0,0.0,4.0
5268,5166213,0,0.0,0,0,0.0,0.0,0.0,WEB,0.0,2022-02-12T08:45:47.000Z,en,0.0,0.0,5.0
5269,5176040,0,0.0,0,0,0.0,0.0,0.0,WEB,0.0,2022-02-14T11:23:01.000Z,en,0.0,42.0,2.0
5270,5184379,0,0.0,0,0,0.0,0.0,0.0,WEB,0.0,2022-02-16T09:59:58.000Z,en,0.0,0.0,2.0
5271,5186649,0,0.0,0,0,0.0,0.0,0.0,WEB,0.0,2022-02-16T21:37:04.000Z,en,0.0,0.0,3.0

# Merging

In [9]:
market1customersnew = pd.read_csv(r"Data/Market1Customers.csv")
market2customersnew = pd.read_csv(r"Data/Market2Customers.csv")
market2customersnew

,Customer ID,Last Used Platform,Is Blocked,Created At,Language,Outstanding Amount,Loyalty Points,Number of Employees
0,3922702,WEB,0,2021-07-12T08:06:47.000Z,en,0,0,NaN
1,4058001,WEB,0,2021-08-05T08:22:35.000Z,en,0,0,NaN
2,4058334,WEB,0,2021-08-05T09:38:09.000Z,en,0,0,NaN
3,4058414,WEB,0,2021-08-05T09:56:57.000Z,en,0,0,NaN
4,4058431,WEB,0,2021-08-05T09:59:51.000Z,en,0,0,NaN
...,...,...,...,...,...,...,...,...
1090,5161258,WEB,0,2022-02-11T07:11:38.000Z,en,0,0,4.0
1091,5166213,WEB,0,2022-02-12T08:45:47.000Z,en,0,0,5.0
1092,5176040,WEB,0,2022-02-14T11:23:01.000Z,en,0,42,2.0
1093,5184379,WEB,0,2022-02-16T09:59:58.000Z,en,0,0,2.0
1094,5186649,WEB,0,2022-02-16T21:37:04.000Z,en,0,0,3.0

In [10]:
market1customersnew.columns

Index(['Customer ID', 'Last Used Platform', 'Is Blocked', 'Created At',
       'Language', 'Outstanding Amount', 'Loyalty Points',
       'Number of employees'],
      dtype='object')

In [11]:
customers = pd.merge(market1customersnew,market2customersnew,on='Customer ID')
customers.to_csv("mergedcustomers.csv")

In [12]:
print(market1deliveries.columns)

print(market2deliveries.columns)

Index(['Task_ID', 'Order_ID', 'Relationship', 'Team_Name', 'Task_Type',
       'Notes', 'Agent_ID', 'Agent_Name', 'Distance(m)',
       'Total_Time_Taken(min)', 'Task_Status', 'Ref_Images', 'Rating',
       'Review', 'Latitude', 'Longitude', 'Tags', 'Promo_Applied',
       'Custom_Template_ID', 'Task_Details_QTY', 'Task_Details_AMOUNT',
       'Special_Instructions', 'Tip', 'Delivery_Charges', 'Discount',
       'Subtotal', 'Payment_Type', 'Task_Category', 'Earning', 'Pricing',
       'Unnamed: 30', 'Unnamed: 31'],
      dtype='object')
Index(['Task_ID', 'Order_ID', 'Relationship', 'Team_Name', 'Task_Type',
       'Notes', 'Agent_ID', 'Distance(m)', 'Total_Time_Taken(min)',
       'Task_Status', 'Ref_Images', 'Rating', 'Review', 'Latitude',
       'Longitude', 'Tags', 'Promo_Applied', 'Custom_Template_ID',
       'Task_Details_QTY', 'Task_Details_AMOUNT', 'Special_Instructions',
       'Tip', 'Delivery_Charges', 'Discount', 'Subtotal', 'Payment_Type',
       'Task_Category', 'Earning', 'Pricing'],
      dtype='object')

In [13]:
mergedcustomers = pd.read_csv(r'merges/mergedcustomers.csv', na_values=['NaN', 'nan'])
mergedcustomers

,Customer ID,Last Used Platform_x,Is Blocked_x,Created At_x,Language_x,Outstanding Amount_x,Loyalty Points_x,Number of employees,Last Used Platform_y,Is Blocked_y,Created At_y,Language_y,Outstanding Amount_y,Loyalty Points_y,Number of Employees
0,3144837,WEB,0.0,2021-03-15T17:13:19.000Z,en,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0
1,3174590,WEB,0.0,2021-03-20T14:15:11.000Z,en,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0
2,3181998,WEB,0.0,2021-03-21T15:36:51.000Z,en,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0
3,3191244,WEB,0.0,2021-03-23T08:54:00.000Z,en,0.0,367.0,0.0,0,0.0,0,0,0.0,0.0,0.0
4,3274222,WEB,0.0,2021-04-06T13:52:39.000Z,en,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5267,5161258,0,0.0,0,0,0.0,0.0,0.0,WEB,0.0,2022-02-11T07:11:38.000Z,en,0.0,0.0,4.0
5268,5166213,0,0.0,0,0,0.0,0.0,0.0,WEB,0.0,2022-02-12T08:45:47.000Z,en,0.0,0.0,5.0
5269,5176040,0,0.0,0,0,0.0,0.0,0.0,WEB,0.0,2022-02-14T11:23:01.000Z,en,0.0,42.0,2.0
5270,5184379,0,0.0,0,0,0.0,0.0,0.0,WEB,0.0,2022-02-16T09:59:58.000Z,en,0.0,0.0,2.0
5271,5186649,0,0.0,0,0,0.0,0.0,0.0,WEB,0.0,2022-02-16T21:37:04.000Z,en,0.0,0.0,3.0

In [14]:
mergedcustomers.drop_duplicates()
mergedcustomers

,Customer ID,Last Used Platform_x,Is Blocked_x,Created At_x,Language_x,Outstanding Amount_x,Loyalty Points_x,Number of employees,Last Used Platform_y,Is Blocked_y,Created At_y,Language_y,Outstanding Amount_y,Loyalty Points_y,Number of Employees
0,3144837,WEB,0.0,2021-03-15T17:13:19.000Z,en,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0
1,3174590,WEB,0.0,2021-03-20T14:15:11.000Z,en,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0
2,3181998,WEB,0.0,2021-03-21T15:36:51.000Z,en,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0
3,3191244,WEB,0.0,2021-03-23T08:54:00.000Z,en,0.0,367.0,0.0,0,0.0,0,0,0.0,0.0,0.0
4,3274222,WEB,0.0,2021-04-06T13:52:39.000Z,en,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5267,5161258,0,0.0,0,0,0.0,0.0,0.0,WEB,0.0,2022-02-11T07:11:38.000Z,en,0.0,0.0,4.0
5268,5166213,0,0.0,0,0,0.0,0.0,0.0,WEB,0.0,2022-02-12T08:45:47.000Z,en,0.0,0.0,5.0
5269,5176040,0,0.0,0,0,0.0,0.0,0.0,WEB,0.0,2022-02-14T11:23:01.000Z,en,0.0,42.0,2.0
5270,5184379,0,0.0,0,0,0.0,0.0,0.0,WEB,0.0,2022-02-16T09:59:58.000Z,en,0.0,0.0,2.0
5271,5186649,0,0.0,0,0,0.0,0.0,0.0,WEB,0.0,2022-02-16T21:37:04.000Z,en,0.0,0.0,3.0

In [23]:
mergedcustomers.fillna(0, inplace=True)
mergedcustomers.to_csv("merges/mergecustomers.csv",index=False)

In [16]:
print(market1orders.columns)

print(market2orders.columns)

Index(['Order ID', 'Order Status', 'Category Name', 'SKU',
       'Customization Group', 'Customization Option', 'Quantity', 'Unit Price',
       'Cost Price', 'Total Cost Price', 'Total Price', 'Order Total',
       'Sub Total', 'Tax', 'Delivery Charge', 'Tip', 'Discount',
       'Remaining Balance', 'Payment Method', 'Additional Charge',
       'Taxable Amount', 'Transaction ID', 'Currency Symbol',
       'Transaction Status', 'Promo Code', 'Customer ID', 'Merchant ID',
       'Description', 'Distance (in km)', 'Order Time', 'Pickup Time',
       'Delivery Time', 'Ratings', 'Reviews', 'Merchant Earning',
       'Commission Amount', 'Commission Payout Status',
       'Order Preparation Time', 'Debt Amount', 'Redeemed Loyalty Points',
       'Consumed Loyalty Points', 'Cancellation Reason', 'Flat Discount',
       'Checkout Template Name', 'Checkout Template Value'],
      dtype='object')
Index(['Order ID', 'Order Status', 'Category Name', 'SKU',
       'Customization Group', 'Customization Option', 'Quantity', 'Unit Price',
       'Cost Price', 'Total Cost Price', 'Total Price', 'Order Total',
       'Sub Total', 'Tax', 'Delivery Charge', 'Tip', 'Discount',
       'Remaining Balance', 'Payment Method', 'Additional Charge',
       'Taxable Amount', 'Transaction ID', 'Currency Symbol',
       'Transaction Status', 'Promo Code', 'Customer ID', 'Merchant ID',
       'Description', 'Distance (in km)', 'Order Time', 'Pickup Time',
       'Delivery Time', 'Ratings', 'Reviews', 'Merchant Earning',
       'Commission Amount', 'Commission Payout Status',
       'Order Preparation Time', 'Redeemed Loyalty Points',
       'Consumed Loyalty Points', 'Cancellation Reason', 'Flat Discount',
       'Checkout Template Name', 'Checkout Template Value'],
      dtype='object')

In [18]:
import pyspark
from pyspark.sql import SparkSession

In [19]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()

In [60]:
customerdata = spark.read.csv("merges/mergecustomers.csv")
customerdata.show()

+-----------+--------------------+------------+--------------------+----------+--------------------+----------------+-------------------+--------------------+------------+------------+----------+--------------------+----------------+-------------------+
|        _c0|                 _c1|         _c2|                 _c3|       _c4|                 _c5|             _c6|                _c7|                 _c8|         _c9|        _c10|      _c11|                _c12|            _c13|               _c14|
+-----------+--------------------+------------+--------------------+----------+--------------------+----------------+-------------------+--------------------+------------+------------+----------+--------------------+----------------+-------------------+
|Customer_ID|Last_Used_Platform_x|Is_Blocked_x|        Created_At_x|Language_x|Outstanding_Amount_x|Loyalty_Points_x|Number_of_employees|Last_Used_Platform_y|Is_Blocked_y|Created_At_y|Language_y|Outstanding_Amount_y|Loyalty_Points_y|Number_of_Employees|
|    3144837|                 WEB|           0|2021-03-15T17:13:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3174590|                 WEB|           0|2021-03-20T14:15:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3181998|                 WEB|           0|2021-03-21T15:36:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3191244|                 WEB|           0|2021-03-23T08:54:...|        en|                   0|             367|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3274222|                 WEB|           0|2021-04-06T13:52:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3289843|                 WEB|           0|2021-04-09T09:51:...|        en|                   0|              21|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3307723|                 WEB|           0|2021-04-12T06:56:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3320505|                 WEB|           0|2021-04-14T06:53:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3320510|                 WEB|           0|2021-04-14T06:54:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3321209|                 WEB|           0|2021-04-14T09:01:...|        en|                   0|               7|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3321648|                 WEB|           0|2021-04-14T10:25:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3321884|                 WEB|           0|2021-04-14T11:07:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3322509|                 WEB|           0|2021-04-14T12:56:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3322639|                 WEB|           0|2021-04-14T13:11:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3326583|                 WEB|           0|2021-04-15T06:23:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3326754|                 WEB|           0|2021-04-15T07:04:...|        en|                   0|               1|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3326869|                 WEB|           0|2021-04-15T07:34:...|        en|                   0|              46|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3327353|                 WEB|           0|2021-04-15T09:38:...|        en|                   0|               2|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3328088|                 WEB|           0|2021-04-15T12:20:...|        en|                   0|               1|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
+-----------+--------------------+------------+--------------------+----------+--------------------+----------------+-------------------+--------------------+------------+------------+----------+--------------------+----------------+-------------------+
only showing top 20 rows

In [61]:
customerdata.na.drop().show()

+-----------+--------------------+------------+--------------------+----------+--------------------+----------------+-------------------+--------------------+------------+------------+----------+--------------------+----------------+-------------------+
|        _c0|                 _c1|         _c2|                 _c3|       _c4|                 _c5|             _c6|                _c7|                 _c8|         _c9|        _c10|      _c11|                _c12|            _c13|               _c14|
+-----------+--------------------+------------+--------------------+----------+--------------------+----------------+-------------------+--------------------+------------+------------+----------+--------------------+----------------+-------------------+
|Customer_ID|Last_Used_Platform_x|Is_Blocked_x|        Created_At_x|Language_x|Outstanding_Amount_x|Loyalty_Points_x|Number_of_employees|Last_Used_Platform_y|Is_Blocked_y|Created_At_y|Language_y|Outstanding_Amount_y|Loyalty_Points_y|Number_of_Employees|
|    3144837|                 WEB|           0|2021-03-15T17:13:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3174590|                 WEB|           0|2021-03-20T14:15:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3181998|                 WEB|           0|2021-03-21T15:36:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3191244|                 WEB|           0|2021-03-23T08:54:...|        en|                   0|             367|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3274222|                 WEB|           0|2021-04-06T13:52:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3289843|                 WEB|           0|2021-04-09T09:51:...|        en|                   0|              21|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3307723|                 WEB|           0|2021-04-12T06:56:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3320505|                 WEB|           0|2021-04-14T06:53:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3320510|                 WEB|           0|2021-04-14T06:54:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3321209|                 WEB|           0|2021-04-14T09:01:...|        en|                   0|               7|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3321648|                 WEB|           0|2021-04-14T10:25:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3321884|                 WEB|           0|2021-04-14T11:07:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3322509|                 WEB|           0|2021-04-14T12:56:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3322639|                 WEB|           0|2021-04-14T13:11:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3326583|                 WEB|           0|2021-04-15T06:23:...|        en|                   0|               0|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3326754|                 WEB|           0|2021-04-15T07:04:...|        en|                   0|               1|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3326869|                 WEB|           0|2021-04-15T07:34:...|        en|                   0|              46|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3327353|                 WEB|           0|2021-04-15T09:38:...|        en|                   0|               2|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
|    3328088|                 WEB|           0|2021-04-15T12:20:...|        en|                   0|               1|                  0|                   0|           0|           0|         0|                   0|               0|                  0|
+-----------+--------------------+------------+--------------------+----------+--------------------+----------------+-------------------+--------------------+------------+------------+----------+--------------------+----------------+-------------------+
only showing top 20 rows

In [38]:
spark

# Spark SQL

In [62]:
customerdata.createOrReplaceTempView("data")
output = spark.sql("SELECT COUNT(*) as total from data")
output.show()

+-----+
|total|
+-----+
| 5273|
+-----+

# Persist data to database

In [63]:
dest_tbl = 'public."spark"'
database = "spark"
password = "eyram"
user = "postgres"

In [67]:
customerdata.write.mode("overwrite") \
    .format("jdbc") \
    .option("url", f"jdbc:postgresql://localhost:5432/{database}") \
    .option("dbtable", customer) \
    .option("user", user) \
    .option("password", password) \
    .option("driver",  "org.postgresql.Driver") \
    .save()

IllegalArgumentException: Option 'dbtable' or 'query' is required.